### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by 18222why** [THU-MIG/RepViT#46]

**Comment by jameslahm** [comment]
Would you mind providing more details?

**Comment by 18222why** [comment]
> Would you mind providing more details?

2024-03-26 09:58:07,728 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2024-03-26 09:58:07,728 - mmdet - INFO - Checkpoints will be saved to /home/sd4t/why/work/RepViT-main/detection/work_dirs/mask_rcnn_repvit_m1_1_fpn_1x_coco by HardDiskBackend.
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main()
  File "train.py", line 234, in main
    train_detector(
  File "/home/sd4t/why/work/RepViT-main/detection/mmdet_custom/apis/train.py", line 180, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 940, in __init__
    self._reset(loader, first_iter=True)
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 971, in _reset
    self._try_put_index()
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1205, in _try_put_index
    index = self._next_index()
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
Here are all the errors. Thank you

**Comment by 18222why** [comment]
> Would you mind providing more details?

Thank you dear teacher,I finished it by change the coco.py

**Comment by 18222why** [comment]
> Would you mind providing more details?
But I have a anew issues:
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main()
  File "train.py", line 234, in main
    train_detector(
  File "/home/sd4t/why/work/RepViT-main/detection/mmdet_custom/apis/train.py", line 180, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    self.call_hook('before_train_epoch')
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/mmdet/datasets/utils.py", line 158, in before_train_epoch
    self._check_head(runner)
  File "/home/sd4t/why/anaconda3/envs/repvit/lib/python3.8/site-packages/mmdet/datasets/utils.py", line 144, in _check_head
    assert module.num_classes == len(dataset.CLASSES), \
AssertionError: The `num_classes` (80) in Shared2FCBBoxHead of MMDataParallel does not matches the length of `CLASSES` 2) in CocoDataset
I want to know the work_dirl how to generate
